### ISSUE TITLE
Install failing - possibly Crystal 0.35.0 related?

### ISSUE THREAD

**Issue by AvnerCohen** [luckyframework/homebrew-lucky#11]
```sh
==> Tapping luckyframework/lucky
Cloning into '/usr/local/Homebrew/Library/Taps/luckyframework/homebrew-lucky'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 426 (delta 20), reused 35 (delta 16), pack-reused 384
Receiving objects: 100% (426/426), 12.42 MiB | 3.42 MiB/s, done.
Resolving deltas: 100% (212/212), done.
Tapped 1 formula (77 files, 30.4MB).
➜  Code brew install lucky
==> Installing lucky from luckyframework/lucky
==> Downloading https://homebrew.bintray.com/bottles/crystal-0.35.0.catalina.bottle.tar.gz
Already downloaded: $HOME/Library/Caches/Homebrew/downloads/202681933b7f8fd9a77cb40117b6e5c6f8853037ffcfc5aa7fac3bfd06e69e30--crystal-0.35.0.catalina.bottle.tar.gz
==> Downloading https://github.com/luckyframework/homebrew-lucky/raw/master/tarballs/lucky-0.21.0.tar.gz
==> Downloading from https://raw.githubusercontent.com/luckyframework/homebrew-lucky/master/tarballs/lucky-0.21.0.tar.gz
######################################################################## 100.0%
==> Installing dependencies for luckyframework/lucky/lucky: crystal-lang
==> Installing luckyframework/lucky/lucky dependency: crystal-lang
==> Pouring crystal-0.35.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/crystal/0.35.0: 1,124 files, 58.4MB
==> Installing luckyframework/lucky/lucky
==> mkdir lib
==> mv teeplate lib/
==> mv lucky_cli lib/
==> crystal build lib/lucky_cli/src/lucky.cr
Last 15 lines from $HOME/Library/Logs/Homebrew/lucky/04.lucky.cr:
2020-06-11 16:02:30 +0300

crystal build lib/lucky_cli/src/lucky.cr

Showing last frame. Use --error-trace for full trace.

In lib/teeplate/src/lib/rendering_entry.cr:204:7

 204 | future do
       ^-----
Error: undefined local variable or method 'future' for Teeplate::RenderingEntry
```

Since installation guide (https://luckyframework.org/guides/getting-started/installing) assumes asdf is used, I am not quite sure why the tap is also installing crystal:

```
==> Installing dependencies for luckyframework/lucky/lucky: crystal-lang
==> Installing luckyframework/lucky/lucky dependency: crystal-lang
==> Pouring crystal-0.35.0.catalina.bottle.tar.gz
```

Maybe this should be removed ?

**Comment by paulcsmith** [comment]
Hi @AvnerCohen! Sorry for the trouble. Lucky does not (yet) support 0.35.0 but will soon.

In the meantime you'll need to use a version manager to install Crystal 0.34.0 then try installing lucky with homebrew. Here are the updated docs: https://luckyframework.org/guides/getting-started/installing#crystal-v0-34-0

LMK if that does the trick!

**Comment by AvnerCohen** [comment]
Thanks @paulcsmith for looking into that.
I might have missed something or maybe there is a misunderstanding.

I am using a version manager for crystal and my global default is set to v0.34.0:

```sh
>$ which crystal
$HOME/.asdf/shims/crystal
$> crystal -v
Crystal 0.34.0 (2020-04-06)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

However, it looks like the brew tap installs crystal (because it is set as a dependency - https://github.com/luckyframework/homebrew-lucky/blob/master/Formula/lucky.rb#L7 ) directly as a brew tap, this installation actually overrides the asdf install:

```sh
$> crystal -v
Crystal 0.35.0 (2020-06-09)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
$> which crystal
/usr/local/bin/crystal
```

At which point the `lucky` install will fail.

I hope this makes sense, if not, happy to get the specifics on what I might be doing wrong.

**Comment by paulcsmith** [comment]
Ah I see. That is a bummer. What if you reinstall asdf *after* installing crystal with homebrew? The other option in the short term is to install the CLI manually using the Linux instructions. It should work identically on macOS: https://luckyframework.org/guides/getting-started/installing#install-lucky-cli-on-linux

**Comment by AvnerCohen** [comment]
Cool, that worked, I guess I'll have to deal with the conflicts if I ever go back to the using the brew tap, but this is good to for now. Thanks !

**Comment by paulcsmith** [comment]
@AvnerCohen Glad that worked! This shouldn't be an issue once Crystal 1.0 lands and there aren't breaking changes. Can't wait!

And welcome to Lucky btw :) Feel free to hop on https://gitter.im/luckyframework/Lobby if you need any help or have ideas for the framework
